import pandas as pd
import numpy as np
from mylinearregression import MyLinearRegression as MLR
import matplotlib.pyplot as plt

df=pd.read_csv('../resources/spacecraft_data.csv')
x1=np.array(df['Age']).reshape((-1,1))
y=np.array(df['Sell_price']).reshape((-1,1))
myLR_age=MLR([[1000],[-1]],alpha=2.5e-5,max_iter=1000000)
myLR_age.fit_(x1,y)
print(f'thetas: {myLR_age.thetas}')
pred=myLR_age.predict_(x1)
plt.grid()
plt.scatter(x1,y,color='midnightblue',label='sell_price')
plt.scatter(x1,pred,color='dodgerblue',label='predicted sell_price')
plt.xlabel('x1: age (in years)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='lower left')
plt.show()
print(myLR_age.mse_(y,pred))

x2=np.array(df['Thrust_power']).reshape((-1,1))
myLR_thrust=MLR([[1000],[-1]],alpha=2.5e-5,max_iter=1000000)
myLR_thrust.fit_(x2,y)
print(f'thetas: {myLR_thrust.thetas}')
pred=myLR_thrust.predict_(x2)
plt.grid()
plt.scatter(x2,y,color='green',label='sell_price')
plt.scatter(x2,pred,color='lime',label='predicted sell_price')
plt.xlabel('x2: thrust power(in 10Km/s)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='upper left')
plt.show()
print(myLR_thrust.mse_(y,pred))

x3=np.array(df['Terameters']).reshape((-1,1))
myLR_distance=MLR([[1000],[-1]],alpha=2.5e-5,max_iter=1000000)
myLR_distance.fit_(x3,y)
print(f'thetas: {myLR_distance.thetas}')
pred=myLR_distance.predict_(x3)
plt.grid()
plt.scatter(x3,y,color='midnightblue',label='sell_price')
plt.scatter(x3,pred,color='dodgerblue',label='predicted sell_price')
plt.xlabel('x3: distance totalizer value of spacecraft (in Tmeters)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='lower left')
plt.show()
print(myLR_distance.mse_(y,pred))

x4=np.hstack((x1,x2,x3))
myLR=MLR([1,1,1,1],alpha=1e-5,max_iter=1280000)
myLR.fit_(x4,y)
print(f'thetas: {myLR.thetas}.')
pred=myLR.predict_(x4)
print(myLR.mse_(y,pred))
plt.grid()
plt.scatter(x1,y,color='green',label='sell_price')
plt.scatter(x1,pred,color='lime',label='predicted sell_price')
plt.xlabel('x1: age (in years)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='lower left')
plt.show()
plt.grid()
plt.scatter(x2,y,color='darkviolet',label='sell_price')
plt.scatter(x2,pred,color='violet',label='predicted sell_price')
plt.xlabel('x2: thrust power(in 10Km/s)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='lower left')
plt.show()
plt.grid()
plt.scatter(x3,y,color='darkviolet',label='sell_price')
plt.scatter(x3,pred,color='violet',label='predicted sell_price')
plt.xlabel('x3: distance totalizer value of spacecraft (in Tmeters)')
plt.ylabel('y: sell price (in keuros)')
plt.legend(loc='lower left')
plt.show()
